name: Build LaTeX document
on:
    push:
        branches:
            - main
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v4
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: |
                      unity_resume.tex
                      react_native_resume.tex
                      backend_resume.tex
                      c++_resume.tex
                      dotnet_resume.tex
                      react_resume.tex
                      python_resume.tex
            - name: Upload PDF file
              uses: actions/upload-artifact@v4
              with:
                  name: PDF
                  path: |
                      unity_resume.pdf
                      react_native_resume.pdf
                      backend_resume.pdf
                      c++_resume.pdf
                      dotnet_resume.pdf
                      react_resume.pdf
                      python_resume.pdf
